### ISSUE TITLE
Executable paths disappearing when upgrading the addon

### ISSUE THREAD

**Issue by filibis** [norgeotloic/BakeMyScan#57]
Hi Loïc,

Executables paths should be remembered after reopening Blender in my opinion (if that's possible).

Thanks for the great addon!

**Comment by norgeotloic** [comment]
Hello Filibis, and thanks for your feedback! 

That behaviour seems strange, as the paths to the executables are correctly saved for me on linux and on Windows upon opening/closing...

**Did you think about saving your user settings AFTER having selected the executables?**

If that's the case, I'll ask you to wait a few hours to try the 1.0.1 version I'm working on, in which I might have fixed this behaviour "by accident". Otherwise, could you tell me which OS/version of blender you're on?

Note that when "upgrading" the addon, you'll have to reconfigure the paths to the executables, which I'll try to fix later...

**Comment by norgeotloic** [comment]
Okay, thanks for reassuring me!
I'll still keep this issue open for the "release upgrade" problem, and renaming it accordingly!
